# Generated by Django 4.0.3 on 2022-03-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_is_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
