# Generated by Django 4.0.3 on 2022-04-12 19:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_estate_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estateimages',
            name='image',
        ),
        migrations.AlterField(
            model_name='estate',
            name='main_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
