# Generated by Django 4.0.3 on 2022-04-12 19:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_estateimages_image_alter_estate_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateimages',
            name='image',
            field=cloudinary.models.CloudinaryField(default='2.png', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
